spring.datasource.password=4563
spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/school-console-app?useSSL=false&serverTimezone=Europe/Kiev
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.application.name=university-cms
server.port=8088


spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration

application.username=john week
application.accountType=Student
spring.jpa.open-in-view=true
